---
  - name:  Replication process script copy to primary node
    template: src={{item.src}} dest={{item.dest}}
    with_items:
      - { src: 'replicaset-process-primary-1.j2', dest: '/tmp/replicaset-process-1.js' }
      - { src: 'replicaset-process-primary-2.j2', dest: '/tmp/replicaset-process-2.js' }
      - { src: 'replicaset-process-primary-3.j2', dest: '/tmp/replicaset-process-3.js' }
      - { src: 'replicaset-process-primary-4.j2', dest: '/tmp/replicaset-process-4.js' }
      - { src: 'replicaset-process-primary-5.j2', dest: '/tmp/replicaset-process-5.js' }
      - { src: 'replicaset-process-primary-6.j2', dest: '/tmp/replicaset-process-6.js' }
      - { src: 'replicaset-process-primary-7.j2', dest: '/tmp/replicaset-process-7.js' }
      - { src: 'replicaset-process-primary-8.j2', dest: '/tmp/replicaset-process-8.js' }
    when: ansible_host == "192.168.24.2"

  - name: Create replicaset in primary node
    shell: mongo -u replica -p replica --authenticationDatabase admin  < /tmp/replicaset-process-1.js
    ignore_errors: yes
    when: ansible_host == "192.168.24.2"
  - pause:
      seconds: 5

  - name: Create replicaset in primary node
    shell: mongo -u replica -p replica --authenticationDatabase admin  < /tmp/replicaset-process-2.js
    ignore_errors: yes
    when: ansible_host == "192.168.24.2"
  - pause:
      seconds: 5
      
  - name: Create replicaset in primary node
    shell: mongo -u replica -p replica --authenticationDatabase admin  < /tmp/replicaset-process-3.js
    ignore_errors: yes
    when: ansible_host == "192.168.24.2"
  - pause:
      seconds: 5

  - name: Create replicaset in primary node
    shell: mongo -u replica -p replica --authenticationDatabase admin  < /tmp/replicaset-process-4.js
    ignore_errors: yes
    when: ansible_host == "192.168.24.2"
  - pause:
      seconds: 5

  - name: Create replicaset in primary node
    shell: mongo -u replica -p replica --authenticationDatabase admin  < /tmp/replicaset-process-5.js
    ignore_errors: yes
    when: ansible_host == "192.168.24.2"
  - pause:
      seconds: 5

  - name: Create replicaset in primary node
    shell: mongo -u replica -p replica --authenticationDatabase admin  < /tmp/replicaset-process-6.js
    ignore_errors: yes
    when: ansible_host == "192.168.24.2"
  - pause:
      seconds: 5

  - name: Create replicaset in primary node
    shell: mongo -u replica -p replica --authenticationDatabase admin  < /tmp/replicaset-process-7.js
    ignore_errors: yes
    when: ansible_host == "192.168.24.2"
  - pause:
      seconds: 5

  - name: Create replicaset in primary node
    shell: mongo -u replica -p replica --authenticationDatabase admin  < /tmp/replicaset-process-8.js
    ignore_errors: yes
    when: ansible_host == "192.168.24.2"
  - pause:
      seconds: 5 

  - name: Replication process script copy to standby node
    template: src={{item.src}} dest={{item.dest}}
    with_items:
      - { src: 'replicaset-process-standby-1.j2', dest: '/tmp/replicaset-process-1.js' }
      - { src: 'replicaset-process-standby-2.j2', dest: '/tmp/replicaset-process-2.js' }
      - { src: 'replicaset-process-standby-3.j2', dest: '/tmp/replicaset-process-3.js' }
    when: ansible_host == "192.168.24.3"   

  - name: Create replicaset in standby node
    shell: mongo -u replica -p replica --authenticationDatabase admin  < /tmp/replicaset-process-1.js
    ignore_errors: yes
    when: ansible_host == "192.168.24.3"
  - pause:
      seconds: 5   

  - name: Create replicaset in standby node
    shell: mongo -u replica -p replica --authenticationDatabase admin  < /tmp/replicaset-process-2.js
    ignore_errors: yes
    when: ansible_host == "192.168.24.3"
  - pause:
      seconds: 5   

  - name: Create replicaset in standby node
    shell: mongo -u replica -p replica --authenticationDatabase admin  < /tmp/replicaset-process-3.js
    ignore_errors: yes
    when: ansible_host == "192.168.24.3"
  - pause:
      seconds: 5   
