-
  name: install tomcat server
  hosts: all  
  become: true
  vars_files:  ## vars yeniki variables. lap basda variable kimi qeyd edirsen. kod hissede ise sade sekilde variableleri yazirsan
    - tomcat_vars  ## hemin dir daxilinde tomcat_vars adinda fayl yaradirsan ve btn variableleri atirsan bu faylaki burada daha seliqeli olsun
  
  tasks:
    - name: install java  ## java son paketi yum install edir
      yum:
        name: java  
        state: latest

    - name: download tomcat server packages
      get_url:
        url: "{{ tomcat_url }}"  ## yuxarida qeyd olunan variableni bu formada qeyd edirik ve get_url ile hemin url i download edir
        dest: /usr/local

    - name: extract tomcat packages
      unarchive:
        src: /usr/local/{{ tomcat_package }}.tar.gz  ## yuxarida qeyd olunan variableni qeyd edirik ve unarchive ile paketi arxivden cixarir
        dest: /usr/local
        remote_src: yes

    - name: start tomcat services
      shell: nohup /usr/local/{{ tomcat_package }}/bin/startup.sh  ## bu komanda ile ise scripti icra edirik